services:
  db:
    image: postgres:16.6
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
