services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      # - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      # - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./init.sh:/docker-entrypoint-initdb.d/init.sh

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080